(function(){var g=void 0,h=true,j=null,k=false,l,n=this;function aa(a){var b=o;function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ba(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function ca(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function da(a,b){var c="",d=ea(encodeURIComponent(a));d.splice(b||5,d.length);q(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ea(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,i=3285377520,p=[],m,w,x,E,y,H=Math.ceil((a.length/4+2)/16),O=[H],A=0,v;A<H;A++){O[A]=[];for(m=0;m<16;m++)O[A][m]=a.charCodeAt(A*64+m*4)<<24|a.charCodeAt(A*64+m*4+1)<<16|a.charCodeAt(A*64+m*4+2)<<8|a.charCodeAt(A*64+m*4+3)}A=(a.length-1)*8;a=H-1;O[a][14]=Math.floor(A/Math.pow(2,32));O[a][15]=A&4294967295;for(A=0;A<H;A++){for(v=0;v<16;v++)p[v]=O[A][v];
for(v=16;v<80;v++)p[v]=(p[v-3]^p[v-8]^p[v-14]^p[v-16])<<1|(p[v-3]^p[v-8]^p[v-14]^p[v-16])>>>31;a=c;m=d;w=e;x=f;E=i;for(v=0;v<80;v++)y=Math.floor(v/20),y=(a<<5|a>>>27)+(y==0?m&w^~m&x:y==1?m^w^x:y==2?m&w^m&x^w&x:m^w^x)+E+b[y]+p[v]&4294967295,E=x,x=w,w=m<<30|m>>>2,m=a,a=y;c=c+a&4294967295;d=d+m&4294967295;e=e+w&4294967295;f=f+x&4294967295;i=i+E&4294967295}return[c,d,e,f,i]}function r(a,b){return function(){a.apply(b,arguments)}}function fa(a){return a.replace(/^www\./,"")}
function s(a,b,c){a.addEventListener?a.addEventListener(b,c,k):a.attachEvent&&a.attachEvent("on"+b,c)}function ga(a,b){var c=n;c.removeEventListener?c.removeEventListener(a,b,k):c.detachEvent&&c.detachEvent("on"+a,b)}function t(a){return typeof a==="number"}function u(a){return typeof a==="string"}function ha(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function z(){return(new Date).getTime()}function ia(a){return encodeURIComponent(a)}
function ja(a,b){if(!(a&&a.constructor===Object)||!(b&&b.constructor===Object))return a===b;var c=0,d=h;q(a,function(a,e){c++;return d=a===b[e]});if(!d)return k;var e=0;q(b,function(){e++});return c===e}function q(a,b){if((!!a&&a.constructor===Object)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===k)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===k)break}}function ka(a,b){var c=[];q(a,function(a){b(a)&&c.push(a)});return c}
function la(a){(!!a&&a.constructor===Object)===h&&(a="");var b={};q(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function ma(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,i=a.length;f<=i;f++)c[0][f]=f;for(var p,m,w,d=1;d<=e;d++)for(f=1;f<=i;f++)p=d-1,m=f-1,w=c[p][m],b.charAt(p)==a.charAt(m)?c[d][f]=w:(m=c[d][m]+1,p=c[p][f]+1,w+=2,c[d][f]=Math.min(m,p,w));return c[b.length][a.length]};var B={},na=1;function C(a,b,c){na++;B[a]=B[a]||{};B[a][na]=[b,c];return na}function D(a){if(u(a))B[a]=g,delete B[a];else if(t(a)){var b=h;q(B,function(c){q(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=k});return b})}}function F(a,b){if(B[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];q(B[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};var G={};
G.d=function(){G.D?G.R("pageload"):(G.Na=[{target:n,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:n,event:"resize"},{target:document.body,event:"mousedown"}],G.W=j,G.na=k,G.C=j,G.Da={},q(G.Na,function(a){var b=a.event;s(a.target,b,function(a){G.R.call(G,b,a)})}),C("focus",function(){G.R("focus")}),G.R("pageload"),s(document.body,"click",function(a){a:if(a=a||window.event){if(a=a.target||a.srcElement,a.tagName!=="A")if(a.parentNode)if(a.parentNode.tagName==="A")a=
a.parentNode;else if(a.parentNode.parentNode&&a.parentNode.parentNode.tagName==="A")a=a.parentNode.parentNode;else{a=g;break a}else{a=g;break a}}else a=g;a&&F("anchor",a)}),G.D=h)};G.Qa=function(){var a,b=G.Da.keydown;if(b===g)return k;b=z()-b;return b<=(a||15E3)&&b>=0};G.sa=100;G.R=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.ob(a);G.W===j?G.Ka():G.na=h};G.ob=function(a){G.Da[a]=z()};
G.Ka=function(){G.W=n.setTimeout(G.Sa,G.sa);F("activity");G.C!==j&&n.clearTimeout(G.C);G.C=n.setTimeout(function(){F("inactive");n.clearTimeout(G.C);G.C=j},5E3+G.sa)};G.Sa=function(){n.clearTimeout(G.W);G.W=j;if(G.na)G.na=k,G.Ka()};var oa=/[?&]__cb_debug=/i;function pa(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function I(a,b){var c=j;b&&(c=b.getAttribute(a));if(c===j){var d=pa(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function qa(a,b,c){return a===g?k:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?k:qa(a.parentNode,b,c)}
function J(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=pa("data-cb-scroll-element"))&&c.length)return c[0][b];if(t(n[a]))return n[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function ra(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function K(){return ra("Height")}
function sa(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function L(){return sa("Height")}function ta(a,b){var c;u(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==document.documentElement;){if(c(a))return a;a=a.parentNode}return j};function M(a){var b=a.offsetHeight,c=a.offsetWidth;(b<=1||c<=1)&&q(a.getElementsByTagName("iframe"),function(a){var e=a.offsetHeight,a=a.offsetWidth;if(e>1&&a>1)return b=e,c=a,k});return{height:b,width:c}}
function ua(a){if(!va(a))return k;if(N(a,"visibility")==="hidden")return k;if(N(a,"overflow")==="hidden"&&(a.offsetHeight===0||a.offsetWidth===0))return k;for(var b=h,c=a.parentElement;c&&b;){var d;var e=c;if(e.scrollHeight===e.clientHeight&&e.scrollWidth===e.clientWidth)d=k;else{d=N(e,"overflow");var f=N(e,"overflow-x"),e=N(e,"overflow-y");d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=wa(a,c));c=c.parentElement}return b&&wa(a,j)}
function wa(a,b){var c,d;if(b){var e=M(b);c=e.width;d=e.height}else c=ra("Width"),d=K();var f=M(a),e=f.height,f=f.width,i=xa(a,b),p=i.y,i=i.x;c=Math.min(i+f,f,c,c-i);d=Math.min(p+e,e,d,d-p);if(c<0||d<0)return k;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function xa(a,b,c){for(var d=a.offsetLeft,e=a.offsetTop,f=k,i=c?0:J("X","Left",g),p=c?0:J("Y","Top",g),m=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===m)d+=a.offsetLeft,e+=a.offsetTop,m=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(N(a,"position")==="fixed"){f=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:i,e-=b?b.scrollTop:p);f&&(d+=i,e+=p);return{x:d,y:e}}
function N(a,b){var c;c=n.getComputedStyle?(c=n.getComputedStyle(a,j))&&(c[b]||c.getPropertyValue(b)):a.currentStyle?a.currentStyle[b]:a.style&&a.style[b];return c||""}function va(a){if("contains"in document.documentElement&&!document.documentElement.contains(a))return k;a=M(a);return a.height>1&&a.width>1};var P={ua:{IDLE:0,ub:1,tb:2,ta:3},j:0};P.d=function(){if(!P.D)C("activity",P.Za,P),C("inactive",P.bb,P),C("focus",P.ab,P),C("blur",P.$a,P),P.D=h};P.ya=function(){return P.j};P.Za=function(){P.j===1?P.o(3):P.j===0&&P.o(2)};P.bb=function(){P.j===3?P.o(1):P.j===2&&P.o(0)};P.ab=function(){(P.j===0||P.j===2)&&P.o(3)};P.$a=function(){P.j===3?P.o(2):P.j===1&&P.o(0)};P.o=function(a){P.j=a;F("state",a)};function ya(a,b){this.da=a||g;this.F=b||g;this.u=this.oa=0}l=ya.prototype;l.d=function(){this.u=this.oa=0;this.K=j;this.nb=C("state",this.B,this);this.B(P.ya())};l.total=function(){this.oa+=this.u;this.u=0;return this.oa};l.B=function(a){n.clearInterval(this.K);this.K=j;if(a===P.ua.ta)this.K=n.setInterval(r(this.fb,this),1E3)};l.fb=function(){if(this.da===g||this.da())this.u++,this.F&&this.F()};l.terminate=function(){n.clearInterval(this.K);this.K=j;D(this.nb)};
l.q=function(){this.terminate();this.F=this.da=g};function za(a,b){this.g=a;this.P=b;this.A=a.getAttribute("data-cb-ad-id")||a.id||"";this.p=j;this.va=0;this.z=new ya(function(){return ua(a)},r(this.F,this));Aa(this);if(this.P)this.Ua=C("activity",this.pa,this)}function Aa(a){a.va++;a.b={};a.b.campaignId="";a.b.creativeId="";a.b.placementId="";a.b.siteId="";a.b.server_height="";a.b.server_width="";a.ca=k;a.Aa=k;a.z.d();a.Ma=k;a.L=0;a.w=j;a.qb=C("state",a.B,a);a.B(P.ya())}l=za.prototype;
l.B=function(a){if(this.w!==j)clearInterval(this.w),this.w=j;this.L=0;if(a===P.ua.ta)this.w=n.setInterval(r(this.pb,this),100);this.P&&this.pa()};l.pb=function(){if(ua(this.g)){if(this.L++,this.L>=10)this.Ma=h,Ba(this),F("forcePing")}else this.L=0};function Ba(a){D(a.qb);n.clearInterval(a.w);a.w=j}l.F=function(){F("adEngaged",this.t(h),this.g);this.P&&this.pa()};function Ca(a,b,c){a.b=b;a.Aa=!!c;F("forcePing")}
l.t=function(a){var b={id:this.A,engagedSeconds:this.z.total()};b.campaignId=this.b?this.b.campaignId:"";b.creativeId=this.b?this.b.creativeId:"";if(a)return b;var a=M(this.g),c=xa(this.g,g,h);b.positionLeft=c.x;b.positionTop=c.y;b.width=a.width;b.height=a.height;b.viewable=this.Ma;b.order=this.va;b.placementId=this.b?this.b.placementId:"";b.siteId=this.b?this.b.siteId:"";b.server_height=this.b?this.b.server_height:"";b.server_width=this.b?this.b.server_width:"";b.lineId=this.b?this.b.lineId:"";b.exclude=
this.ca;return b};l.X=function(){if(!this.Aa){var a=this.g,b={};b.campaignId=I("data-cb-campaign-id",a)||"";b.creativeId=I("data-cb-creative-id",a)||"";b.placementId=I("data-cb-placement-id",a)||"";b.siteId=I("data-cb-site-id",a)||"";b.server_height=I("data-cb-creative-height",a)||"";b.server_width=I("data-cb-creative-width",a)||"";b.lineId=I("data-cb-line-id",a)||"";if(I("data-cb-exclude",a))this.ca=h;ja(b,this.b)||Ca(this,b)}};
l.pa=function(){function a(a,b,c){var d=document.createElement("div"),e=document.createElement("span");e.setAttribute("style","font-weight: bold;");e.textContent=a;d.textContent=b;d.insertBefore(e,d.firstChild);c.appendChild(d)}var b=this.g;if(b){var c;if(this.p)c=document.getElementById(this.p);else{this.p="engagementLog-"+this.A+"-"+ca();c=document.createElement("div");c.setAttribute("id",this.p);document.body.appendChild(c);var d=b.getAttribute("style")||"",e=N(b,"position"),e=e==="fixed"||e===
"absolute"||e==="relative"?"":"position: relative;";d+="box-shadow: 0px 0px 0px 3px #49A2DC; z-index: 2000;"+e;b.setAttribute("style",d);var f="box-shadow: 0px 0px 0px 3px #5BC3BD, 10px 5px 5px #C8DAE8; z-index: 2000;"+e;c.onmouseover=function(){b.setAttribute("style",f)};c.onmouseout=function(){d?b.setAttribute("style",d):b.removeAttribute("style")}}c.innerHTML="";var i=xa(b),e=i.y,i=i.x;e+=J("Y","Top",g);i+=J("X","Left",g);c.setAttribute("style","background-color: #F1F7FB; z-index: 9000000; position: absolute; padding: 10px; border-radius: 5px; font-size: 12px; color: #658BA1; border: 1px solid #C8DAE8; margin: 3px; font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif; top: "+
e+"px; left: "+i+"px;");e=this.t();a("Ad Name: ",e.id+" ["+e.width+"x"+e.height+"]",c);(i=e.campaignId)&&a("Campaign: ",i,c);(i=e.creativeId)&&a("Creative: ",i,c);a("Viewable: ",e.viewable+"",c);c.appendChild(document.createElement("br"));i=ua(this.g);a((i?"In ":"Out Of ")+" View","",c);i&&a("in view intervals: ",this.L+"",c);a("Engaged Time: ",e.engagedSeconds+" seconds",c)}};l.reset=function(){Ba(this);this.z.terminate();Aa(this)};
l.q=function(){Ba(this);this.z.q();this.b=this.g=this.z=j;if(this.p){var a=document.getElementById(this.p);(a.parentElement?a.parentElement:a.parentNode).removeChild(a)}this.P&&D(this.Ua)};function Da(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),q(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Ea(a,b,c){var d="",e=n.location.href.split("?");e.length&&(e=Da(e[1]),b=c||b,e[b]&&(d="&"+a+"="+e[b]));return d}function Fa(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Ga(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=n.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=Fa(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Fa(b.protocol,b.port))b.port="";return b}
function Ha(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function Q(a,b,c){a[b]=a[b]||c}function Ia(a){q(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=Da(b.src.split("?")[1]),Q(a,"uid",b.uid),Q(a,"domain",b.domain),k})}function R(a,b,c){return a[c]?"&g"+b+"="+encodeURIComponent(a[c]):""}function Ja(a){var b=[];q(a,function(a,d){d.charAt(0)=="_"&&b.push(d+"="+a)});return b.length?"&"+b.join("&"):""};var S={};S.Ra=function(){try{S.create("_cb_test","1",1);var a=S.c("_cb_test");S.remove("_cb_test");return a==="1"}catch(b){return k}};S.c=function(a){a+="=";var b="";q(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),k});return b};S.create=function(a,b,c){var d=n._sf_async_config;if(!d||!d.noCookies)d=new Date,d.setTime(z()+c*1E3),document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"};
S.remove=function(a){S.c(a)&&S.create(a,"",-86400)};var T={};T.f=function(a){var b=n._sf_async_config;if(!a&&b&&b.noCookies)return j;if(T.f.aa!==g)return T.f.aa;var a=z()+"",c,d;try{if((d=n.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return T.f.aa=d}catch(e){}return T.f.aa=j};T.c=function(a){var b=T.f();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&z()>c)?(T.remove(a),""):b.getItem(a)||""};
T.create=function(a,b,c){var d=T.f();if(d){var e=new Date;e.setTime(z()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};T.remove=function(a){var b=T.f();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Ka(a){this.U=a||"";this.Ta=T.f()!==j||S.Ra();this.ma=k;La(this)}l=Ka.prototype;l.isSupported=function(){return this.Ta};
function La(a){if(!S.c("_cb_ls")){var b=T.f()!==j,c=S.c("_SUPERFLY_nosample");c&&q(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,h)});var d=S.c("_chartbeat3");d&&(a.create("_v__chartbeat3",d,2592E3,h),S.remove("_chartbeat3"));b&&((b=S.c("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,h),(b=S.c("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,h),(b=S.c("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));S.create("_cb_ls","1",2592E3)}}
function Ma(a){var b=a.ma;a.ma=k;return b}l.create=function(a,b,c,d){a=d?a:this.U+a;(T.f()?T:S).create(a,b,c);T.f()&&S.create(a,b,c)};l.update=function(a,b,c,d,e,f){a=d?a:this.U+a;e=u(e)?e:"::";d=(d=this.c(a,h))?d.split(e):[];t(f)&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,h)};
l.c=function(a,b){var a=b?a:this.U+a,c=(T.f()?T:S).c(a);if(!c&&T.f()&&(c=S.c(a))&&S.c("_cb_ls")){this.ma=h;var d;switch(a){case "_SUPERFLY_nosample":d=600;break;case "_chartbeat4":d=3600;break;case "_cb_cp":d=3600;break;case "_chartbeat3":d=2592E3;break;default:d=94608E3}T.create(a,c,d)}return c};l.remove=function(a,b){a=b?a:this.U+a;(T.f()?T:S).remove(a);T.f()&&S.remove(a)};var U=function(){var a,b;q(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof document[a]==="boolean")return b=c,k});var c={};if(b!==g)c.za=a,c.ra=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),c.Z=b+"visibilitychange";return c}();
U.d=function(){if(!U.D)U.Q=U.Ia(),U.Z&&document.addEventListener&&document.addEventListener(U.Z,U.lb,k),U.wa("focus","onfocusin",U.ia),U.wa("blur","onfocusout",U.Ha),U.Q&&U.ia(),U.D=h};U.vb=function(){return U.Q};U.ia=function(){U.Q=h;F("focus")};U.Ha=function(){U.Q=k;F("blur")};U.wa=function(a,b,c){n.addEventListener?n.addEventListener(a,c,k):document.attachEvent&&document.attachEvent(b,c)};
U.Ia=function(){var a=h;document.hasFocus&&(a=document.hasFocus());var b=k;U.za&&(b=document[U.za]);return a&&!b};U.lb=function(){U.Ia()?U.ia():U.Ha()};function Na(a){var b=j;if(a&&(b=Oa()))return b;var c=n.location,b=V(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Oa(){var a=j;q(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=Ga(b.href),a=V(b.pathname)+b.search+b.hash,k});return a}
for(var Pa={},Qa=0;Qa<81;Qa++)Pa["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Qa)]=h;function Ra(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Pa[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function V(a){if(!u(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Ra);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function o(){this.a=n._sf_async_config||{};this.ba=r(this.kb,this);this.r=[];this.e=new Ka(this.La);this.n=k;this.h=new ya;this.ja=r(this.G,this);s(n,"unload",this.ja);Sa(this)||this.d()}function Sa(a){if(U.ra&&document[U.ra]==="prerender"){a.n=h;var b=r(function(){if(this.n&&document[U.ra]!=="prerender")this.n=k,this.d(),W(this),window.setTimeout(function(){document.removeEventListener(U.Z,b,k)},100)},a);document.addEventListener(U.Z,b,k);return h}return k}l=o.prototype;
l.d=function(){this.fa=this.m=0;this.J=z();this.I=da(Ta(this));this.v=h;this.Ea=72E5;var a=+this.a.sessionLength;if(!isNaN(a)&&this.La!=="_p_")this.Ea=a*6E4;this.h.d();P.d();G.d();U.d();this.l=0;this.Pa=C("activity",this.ha,this)};function W(a){if(!a.e.c("_SUPERFLY_nosample")&&!a.n)a.hb?a.la():(a.hb=h,!n._sf_async_config&&!n._cbq?(a.S=r(a.la,a),s(n,"load",a.S)):a.la())}l.la=function(){var a=n._sf_startpt,b=n._sf_endpt;if(t(a))this.T=t(b)?b-a:z()-a;G.d();this.gb=setInterval(r(this.Fa,this),15E3);this.Fa()};
l.Fa=function(){var a=this.h.u,a=this.a.reading&&+this.a.reading||a>0;this.fa<this.m&&!a?this.fa++:(a?this.m=0:Ua(this),this.fa=0,this.r.push(0),this.r.length>18&&this.r.shift(),z()-this.J>=this.Ea?this.terminate():this.H())};l.kb=function(){this.r.push(1);var a=0;q(this.r,function(b){a+=b});a<3?(this.v=h,Ua(this)):(this.terminate(),this.e.create("_SUPERFLY_nosample","1",600))};l.G=function(){};l.ha=function(){var a=X(this);this.l=Math.max(this.l,a)};
function X(a){return J("Y","Top",!!a.a.scrollElement)}function Ua(a){var b=a.m,b=b?Math.min(b*2,16):1;a.m=b}l.Y=function(a,b){if(!this.n)this.G(),this.terminate(),this.M=n.location.protocol+"//"+this.a.domain+this.a.path,this.a.path=V(a),b&&(this.a.title=b),this.d(),W(this)};function Va(a){if(a.M)return h;a=(document.referrer||"").indexOf("://"+n.location.host+"/");return a!=-1&&a<9}
function Wa(a){a=a.M;if(!a&&(a=document.referrer||"")){var b=Ga(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=V(b.pathname),a=Ha(b)}return encodeURIComponent(a)}function Xa(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}
function Ta(a){var b=n.navigator,c=n.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];q(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=n.performance;d=d.concat([b&&b.now?b.now():"",Wa(a),document.title,n.location.href,z(),sa("Width"),L(),ca()]);return d.join()}function Ya(a){var b="",c=a.e.c("_chartbeat4");c&&(q(c.split("::"),function(a){b+="&z="+encodeURIComponent(a)}),a.e.remove("_chartbeat4"));return b}
function Za(a){var a=(a.e.c("_chartbeat2",h)||"").split("."),b=z(),c=b-+(a[1]||0);b-=+(a[2]||0);return a[0]&&c>18E5&&b<2592E6?0:1}l.terminate=function(){this.h.terminate();D(this.Pa);this.S!==g&&ga("load",this.S);clearInterval(this.gb)};l.q=function(){this.terminate();ga("unload",this.ja);this.ja=this.S=this.e=this.r=this.ba=this.a=j;this.h.q();this.h=j};function Y(){this.i=[];this.ka=[];"postMessage"in window&&s(window,"message",r(this.eb,this));this.La="_p_";this.wb=j;s(n,"beforeunload",r(this.jb,this));o.call(this)}aa(Y);var $a=0;l=Y.prototype;
l.d=function(){Y.V.d.call(this);var a=n.location;Q(this.a,"pingServer","ping.chartbeat.net");Q(this.a,"endServer","edge01.chartbeat.net");Q(this.a,"title",document.title);Q(this.a,"domain",a.host);Q(this.a,"path",Na(!!this.a.useCanonical));Q(this.a,"engaged",k);a=n.location.search||"";if(a.match(oa))a=Da(a).__cb_debug,$a=parseInt(a,10);this.O=this.a.adIdentifier||"data-cb-ad-id";this.a.domain=fa(this.a.domain);this.ga=Za(this);this.k=this.e.c("_chartbeat2",h);this.s=this.Ba=0;this.Ya=function(){var a=
z()-this.Ba;a<250?(this.s&&n.clearTimeout(this.s),this.s=n.setTimeout(r(this.H,this),a)):this.v||this.H()};this.Xa=C("forcePing",this.Ya,this);if(!this.k)this.a.utoken?this.k=this.a.utoken:(this.k=da(Ta(this),3),this.a.utoken=this.k);this.k=this.k.split(".")[0];ab(this);bb(this);if((a=this.a.engagedAdFilters)&&a.length){this.a.engagedAdFilters=[];var b=this;q(a,function(a){b.N(a)})}this.Wa=C("adEngaged",this.Va,this);this.ka=[]};l.jb=function(){this.H(h)};
l.G=function(){this.e.update("_chartbeat4",["t="+this.I,"E="+this.h.total(),"ad="+ia(cb(this)),"x="+X(this),"c="+Math.round((z()-this.J)/600)/100,"y="+L(),"w="+K()].join("&"),3600)};
function cb(a){var b=[];q(a.i.concat(a.ka),function(a){var a=a.t?a.t():a,d=encodeURIComponent(a.id),e=a.engagedSeconds,f=a.positionLeft,i=a.positionTop,p=a.width,m=a.height,w=encodeURIComponent(a.creativeId||""),x=encodeURIComponent(a.campaignId||""),E=encodeURIComponent(a.placementId||""),y=encodeURIComponent(a.siteId||""),H=encodeURIComponent(a.server_height||""),O=encodeURIComponent(a.server_width||""),A=encodeURIComponent(a.lineId||""),v=a.order,kb=a.refreshed||"0",lb=a.viewable?"1":"0";a.exclude&&
(x="");b.push(d+"="+[e,f,i,p,m,x,w,v+"."+kb,lb,E,y,H,O,A].join("::"))});return b.join("&")}
l.H=function(a){this.Ba=z();var b=this.a,c=X(this);this.l=Math.max(this.l,c);this.s&&n.clearTimeout(this.s);var d="",e="";if(this.v)this.v=k,d=(Va(this)?"&v=":"&r=")+Wa(this),this.M&&(d+="&vp=1"),e="&i="+Xa(this);var f=this.T?"&b="+this.T:"";Na(!!b.useCanonical);var i=!b.noCookies&&this.e.isSupported(),a="https://"+(a?b.endServer:b.pingServer)+"/ping/ad?h="+encodeURIComponent("ads."+b.domain)+"&p="+encodeURIComponent(b.path)+"&u="+this.k+"&d="+ia(fa(n.location.host))+"&g="+b.uid+R(b,0,"sections")+
R(b,1,"authors")+R(b,2,"zone")+R(b,3,"sponsorName")+R(b,4,"type")+(i?"&n="+this.ga:"&nc=1")+"&c="+Math.round((z()-this.J)/600)/100+"&x="+c+"&m="+this.l+"&y="+L()+"&o="+sa("Width")+"&w="+K()+"&j="+(a?0:Math.round((this.m+2)*15E3/1E3))+"&E="+this.h.total()+d+f+"&t="+this.I+"&V=39"+e+"&tz="+(new Date).getTimezoneOffset()+(Ma(this.e)?"&l=1":"")+Ja(b)+"&ad="+ia(cb(this))+(a?"":Ya(this))+(a?"&zz=1":"")+"&_";this.n||ba(a,this.ba)};
function db(a){a=pa(a.O,"div");return ka(a,function(a){a=M(a);return a.height>1&&a.width>1})}function ab(a){var b=db(a);q(b,function(b){if(!eb(a,b)){var d=new za(b,$a);a.i.push(d);d.X();if(b=I("data-cb-engaged-seconds",b))d=d.t(h),d.engagedSeconds=parseInt(b,10),a.N(d)}});fb(a)}function fb(a){var b=[];q(a.i,function(a){va(a.g)?b.push(a):a.q()});a.i=b}function eb(a,b){var c=k;q(a.i,function(a){if(a.g===b)return c=h,k});return c}l.X=function(){q(this.i,function(a){a.X()})};
l.ha=function(){Y.V.ha.call(this);ab(this)};l.eb=function(a){this.Ca(la(a.data),a.source)};
l.Ca=function(a,b){if(a.cbType!=="campaignMessage")return k;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return k}ab(this);var d=document.getElementsByTagName("iframe"),e=g;q(d,function(a){if(a.contentWindow===c)return e=a,k});if(!e)return k;var f=e.getAttribute(this.O);if(f===j){d=qa(e,this.O);if(d===k)return k;f=d.getAttribute(this.O)}var i=g;q(this.i,function(a){if(f===a.A)return i=a,k});if(i===g)return k;Ca(i,a,h);if(a.exclude)i.ca=h;if(a.engagedSeconds)d=
{id:i.A},d.campaignId=a.campaignId,d.creativeId=a.creativeId,d.engagedSeconds=parseInt(a.engagedSeconds,10),this.N(d);d="cbdata::ack::"+this.I;"postMessage"in b&&b.postMessage(d,"*");return d};l.Y=function(){this.G();this.terminate();this.M=n.location.protocol+"//"+this.a.domain+this.a.path};
l.N=function(a){if(a&&t(a.engagedSeconds)&&!isNaN(a.engagedSeconds)){var b=this.a.engagedAdFilters;if(!b||b.length===g)this.a.engagedAdFilters=[],b=this.a.engagedAdFilters;var c={};c.engagedSeconds=a.engagedSeconds;q(["id","campaignId","creativeId"],function(b){u(a[b])&&(c[b]=a[b])});var d=k;q(b,function(a){d=ja(a,c);return!d});d||b.push(c)}};
l.Va=function(a,b){var c=this.a.engagedAdCallback;if(c){var d=this.a.engagedAdFilters;if(d&&d.length&&a){var e=a.engagedSeconds;q(d,function(d){if(d.engagedSeconds===e){var i=h;q(d,function(b,c){return i=b===a[c]});if(i)return a.element=b,c(a,e),k}})}}};l.mb=function(a){if(a){var b;q(this.i,function(c){if(c.A===a||c.g===a)return b=c,k});if(b){var c=b.t();c.refreshed="1";this.ka.push(c);b.reset()}}};
function bb(a){if($a===1){var b=document.createElement("div");b.setAttribute("style","position:fixed; left:0; right:0 ;top:0 ;bottom:0; background-color: rgba(0, 0, 0, 0.3); z-index:1000;");document.body.appendChild(b);var c=document.createElement("div");document.body.appendChild(c);var d=a.a;q(["sections","zone","sponsorName","type"],function(a){if(d[a]!==g){var b=document.createElement("div");b.textContent=a+": "+d[a];c.appendChild(b)}});c.children.length&&(a="background-color: #F1F7FB; z-index: 9000000; position: fixed;padding: 10px; border-radius: 5px; font-size: 12px;color: #658BA1; border: 1px solid #C8DAE8;font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif;top: "+
Math.round(K()*0.9)+"px;left: "+Math.round(ra("Width")*0.45)+"px;",c.setAttribute("style",a))}}l.terminate=function(){D(this.Xa);D(this.Wa);q(this.i,function(a){a.q()});this.i=[];n.clearTimeout(this.s);Y.V.terminate.call(this)};if(!n.pSUPERFLY_pub){var gb=new Y;n.pSUPERFLY_pub=gb;Y.prototype.virtualPage=Y.prototype.Y;Y.prototype.addEngagedAdFilter=Y.prototype.N;Y.prototype.refreshAd=Y.prototype.mb;Y.prototype.updateCampaignData=Y.prototype.X;if("postMessage"in window!==h)Y.prototype.loadCampaign=Y.prototype.Ca;W(gb)};function hb(){var a=document.createElement("script");a.async=h;a.src=(n.location.protocol||"http:")+"//static.chartbeat.com/js/inpage.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function ib(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=T.f(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),hb())}};function jb(a,b){for(var c=b||document.documentElement,d=[],e=j,f=a,i,p,m,w,x,E;f&&f!==c;){i=f.nodeName.toLowerCase();e=f;p=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){m=f.children;w=0;for(x=0,E=m.length;x<E;x++){if(e===m[x]){i+="["+(1+x-w)+"]";break}m[x].nodeName!==p&&w++}}d.unshift(i)}return d.join("/")};function Z(){o.call(this);for(var a=r(this.Ja,this),b=n._cbq||[];b.length;)a(b.shift());n._cbq={push:a};C("anchor",this.ib,this);"postMessage"in window&&s(n,"message",r(this.cb,this))}aa(Z);l=Z.prototype;
l.d=function(){Z.V.d.call(this);this.$=j;Ia(this.a);var a=n.location;Q(this.a,"pingServer","ping.chartbeat.net");Q(this.a,"title",document.title);Q(this.a,"domain",a.host);this.a.path=this.a.path?V(this.a.path):Na(!!this.a.useCanonical);this.ea=fa(a.host);this.a.domain=fa(this.a.domain);a=(this.e.c("_chartbeat2",h)||"").split(".");a.length>4&&(a=[]);var b=z(),c,d="1",e=a&&+a[2];c=a&&a[3];if(a&&e&&c)if(d=Math.abs((ha(b)-ha(e))/864E5)){d=Math.min(d,16)-1;for(e="";d--;)e+=0;d=(c+e+"1").slice(-16)}else d=
c;c=d;this.ga=Za(this);a[0]||(a[0]=this.a.utoken||da(Ta(this),3),a[1]=b);a[2]=b;a[3]=c;this.qa=a[0];this.k=a.join(".");this.e.create("_chartbeat2",this.k,94608E3,h);this.a.utoken=this.qa;var f;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)f=(Math.min((Math.abs((ha(c)-ha(b))/864E5)||0)+1,16,a.length)-1).toString(16),f+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.xa=f};l.Oa=function(a){this.$=a};
l.G=function(){this.e.update("_chartbeat4",["t="+this.I,"E="+this.h.total(),"x="+X(this),"c="+Math.round((z()-this.J)/600)/100,"y="+L(),"w="+K()].join("&"),3600)};
l.H=function(){var a=this.a,b=X(this);this.l=Math.max(this.l,b);var c=Math.round((z()-this.J)/600)/100,d=0,e=0,f=0,i=this.h.u;G.Qa()?e=1:this.a.reading&&+this.a.reading||i>0||c<0.09?d=1:f=1;var p="",m="",w="",x="",E="",y=Va(this);if(this.v){this.v=k;var p=(y?"&v=":"&r=")+Wa(this),m="&i="+Xa(this),H=this.a.hudTrackable;H!==g&&(w="&L="+(H?"1":"0"));if(y&&(y=mb(this)))p="&v="+encodeURIComponent(y.path),x="&K="+[y.left,y.top,y.sb,encodeURIComponent(y.rb)].join("::"),y.Ga>1&&(x+="&l1="+y.Ga);a.alias&&
(E="&PA="+encodeURIComponent(a.alias));this.M&&(p+="&vp=1")}y=this.T?"&b="+this.T:"";H=this.$?"&A="+this.$:"";a=(n.location.protocol||"http:")+"//"+a.pingServer+"/ping?h="+encodeURIComponent(a.domain)+"&p="+encodeURIComponent(a.path)+"&u="+this.qa+"&d="+encodeURIComponent(this.ea)+"&g="+a.uid+R(a,0,"sections")+R(a,1,"authors")+R(a,3,"sponsorName")+R(a,4,"type")+(!a.noCookies&&this.e.isSupported()?"&n="+this.ga:"&nc=1")+(this.xa?"&f="+this.xa:"")+"&c="+c+"&x="+b+"&m="+this.l+"&y="+L()+"&o="+sa("Width")+
"&w="+K()+"&j="+Math.round((this.m+2)*15E3/1E3)+"&R="+d+"&W="+e+"&I="+f+"&E="+this.h.total()+"&e="+i+p+x+E+y+H+Ea("C","utm_campaign",a.campaignTag)+Ea("M","utm_medium",a.mediumTag)+"&t="+this.I+"&V=39"+Ya(this)+m+w+"&tz="+(new Date).getTimezoneOffset()+(Ma(this.e)?"&l=1":"")+Ja(a)+"&_";this.n||ba(a,this.ba)};
l.cb=function(a){var b=this.a;if(a.origin==="http://"+(b.playerdomain||this.ea)){var c=a.data;u(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Ja(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+Xa(this)+"&referrer="+Wa(this)+"&internal="+(Va(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ea)+"&utoken="+this.qa,a.source.postMessage(b,"*"))}};
l.Ja=function(a){this.a[a[0]]=a[1];this.m=0};function nb(a){a=a.replace(/-{2,}/g,"-");a=Ga(a);a.pathname=V(a.pathname);return a}
l.ib=function(a){var b=a.href||"",b=nb(b);if(!(b.hostname!==n.location.hostname||b.protocol.indexOf("http")!==0)){var b=Ha(b),c=ta(a,function(a){return a.id}),d=jb(a,c);c&&(d&&(d="/"+d),d="*[@id='"+c.id+"']"+d);c=da(d);d=encodeURIComponent(d).replace(/-/g,"%2D");d.length>512&&(d="");a=xa(a,g,h);this.e.update("_chartbeat5",[a.x,a.y,encodeURIComponent(this.a.path),encodeURIComponent(b),c,d].join(","),60,k,g,5)}};
function mb(a){var b=a.e.c("_chartbeat5");if(!b)return j;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,i=nb(n.location.href),p=Ha(i);q(c,function(a,b){var c=a.split(","),i=ma(p,decodeURIComponent(c[3]));if(i===0)return d=c,e=b,k;if(f===g||i<f)f=i,d=c,e=b})}c.splice(e,1);a.e.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),sb:d[4]||"",rb:a,Ga:b}};if(!n.pSUPERFLY){var ob=new Z;n.pSUPERFLY=ob;Z.prototype.virtualPage=Z.prototype.Y;Z.prototype.activity=Z.prototype.Oa;var $=n.pSUPERFLY_pub;$&&$.virtualPage&&(Z.prototype.virtualPage=function(){var a=arguments.length?Array.prototype.slice.call(arguments,0):[];$.virtualPage();Z.prototype.Y.apply(ob,a);$.d();W($)});$&&$.addEngagedAdFilter&&(Z.prototype.addEngagedAdFilter=r($.addEngagedAdFilter,$));$&&$.refreshAd&&(Z.prototype.refreshAd=r($.refreshAd,$));W(ob);var pb=T.f(h);if(pb){s(n,"message",ib);
var qb;if(qb=pb.getItem("_cb_ip")){var rb=n.location;qb=!(!/^([^.]+[.])?chartbeat\.com$/.test(rb.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(rb.pathname))}qb&&hb()}};})();
